import Head from 'next/head'
import styles from '../styles/Home.module.css'

import type { GetStaticProps, NextPage } from 'next'
import { Character, GetCharacterResults } from '../types'
import Image from 'next/image'
import imageLoader from '../imageLoader'
import Link from 'next/link'

const Home: NextPage<{characters: Character[]}> = ({characters}) => {
  // NextPage is a generic, and we use this generic to type our characters
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      {characters.map((char) => {
        return (
          <div key={char.id}>
            <Link href={`/characters/${char.id}`}>
              {/* Link passes the href on to the next element. So in the <a> */}
              <a>
                <h3>{char.name}</h3>
              </a>
            </Link>
            <Image
              loader={imageLoader}
              unoptimized
              // prevents Next.js from optimizing images, since they are hosted already 
              src={char.image}
              alt={char.name}
              width='200'
              height='200'
            />
          </div>
          
        )
      })}
    </div>
  )
}

// TS Notes
  // GetStaticProps type comes Next.js itself
  // To get types for result, check in the parameters of NextPage above. Destructured the props.. {characters}
export const getStaticProps: GetStaticProps = async(context) => {
  const res = await fetch("https://rickandmortyapi.com/api/character")
  const {results}: GetCharacterResults = await res.json() 

  return {
    props: {
      characters: results
    }
  }
}
// Runs when you build your application
// alternative is getServerSideProps
// but server-side props means you have to run your application in lambda functions 

export default Home
